# Generated by Django 3.1.7 on 2021-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phn', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=250)),
                ('billing_street', models.CharField(max_length=250)),
                ('billing_city', models.CharField(max_length=250)),
                ('billing_state', models.CharField(max_length=250)),
                ('billing_country', models.CharField(max_length=250)),
            ],
        ),
    ]
