# Generated by Django 3.1.7 on 2021-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(choices=[('Bamboo', 'Bamboo'), ('Gas', 'Gas'), ('Umbrella', 'Umbrella'), ('Clampett Oil and Gas Corp', 'Clampett Oil and Gas Corp'), ('Pipes', 'Pipes'), ('Milk', 'Milk')], default='1', max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
