# Generated by Django 3.1.7 on 2021-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Clampett Oil and Gas Corp', 'Clampett Oil and Gas Corp'), ('Umbrella', 'Umbrella'), ('Bamboo', 'Bamboo'), ('Gas', 'Gas'), ('Pipes', 'Pipes')], default='1', max_length=250),
        ),
    ]
